### ISSUE TITLE
ImmediateScheduler not returning immediately with debounce

### ISSUE THREAD

**Issue by madsodgaard** [pointfreeco/combine-schedulers#11]
**Describe the bug**
I am trying to use `ImmediateScheduler` to avoid using `XCTWaiter` to wait for a given `debounce` to finish. However, when I pass in a immediate scheduler to `debounce()` the value assigned by the subscriber is not set before the assertion happens. It won't even work if I add `_ = XCTWaiter.wait(for: [XCTestExpectation()], timeout: 5)` even though the debounce is only for 0.5 seconds.

The test succeeds if I use `DispatchQueue.main` and wait for 0.5 seconds. It might just be me understanding the functionality of purposes for `ImmediateScheduler`

```swift
// I am passing in a scheduler variable normally instead of hardcoding, just for demonstration purposes.
usernameState
            .debounce(for: 0.5, scheduler: DispatchQueue.immediateScheduler)
            .receive(on: DispatchQueue.immediateScheduler)
            .map { $0.message }
            .assign(to: \.usernameError, on: self)
            .store(in: &cancellables)

// Test:
func testUsernameErrorMessage() throws {
        var usernameError = ""
        
        viewModel.$usernameError
            .sink(receiveValue: { usernameError = $0 })
            .store(in: &cancellables)

        // Empty state
        viewModel.username = ""
        XCTAssertEqual(usernameError, "my error message")
}
```

**Expected behavior**
I expected the publisher to return the value immediately instead of having to wait, however it won't even work with an `ImmediateScheduler` if I add `XCTWaiter`.

**Environment**
 - Xcode 12 beta 6
 - Swift 5.3
 - OS (if applicable): iOS 14

**Comment by stephencelis** [comment]
Hey @madsodgaard! Thanks for taking the time to open this. Unfortunately Apple's more complex operators, like `Debounce`, `Throttle`, and `Timer.Publisher` are not compatible with our immediate scheduler (or even the `ImmediateScheduler` that ships with Combine), so this isn't something we can fix. But arguably we might not even _want_ to fix this, because these operators introduce subtle logic into your code that should definitely be tested! `ImmediateScheduler` is mostly useful for simplifying tests that use `receive(on:)`s but otherwise introduce no significant logic to your application.

I've opened up #12 to document this a bit better.

**Comment by stephencelis** [comment]
Closing with the merge of docs in #12, but lemme know if you have any questions!
