### ISSUE TITLE
UIScheduler SchedulerOptions type?

### ISSUE THREAD

**Issue by ollitapa** [pointfreeco/combine-schedulers#22]
Why does the UIScheduler have `public typealias SchedulerOptions = Never`? It does not seem to fit to an API with `AnySchedulerOf<DispatchQueue>` because the `SchedulerOptions` types do not match. Or am I supposed to use `AnySchedulerOf<UIScheduler>` for the API type if I want to also enable use of test scheduler? But then I can not replace the UIScheduler with `DispatchQueue.main`. 

I'm just wondering this because in ReactiveSwift the UIScheduler conforms to their own `Scheduler` protocol (immediate scheduling only) and DispatchQueue conforms to `DateScheduler: Scheduler` protocol (can schedule to the future). So if the API defines `var scheduler: Scheduler` both UIScheduler and DispatchQueue.main can be used. 

I'm not even sure if there is any use case to actually replace `UIScheduler` with plain `DispatchQueue`. I was just used to writing this kind of API 😅

**Comment by stephencelis** [comment]
The main reason we omitted the options here was because they don't seem to apply to the immediacy of a UI Scheduler.

I think generally you'd want to use `AnySchedulerOf<UIScheduler>` in your application if you want to override it with a `TestScheduler` in your tests.

> I'm not even sure if there is any use case to actually replace UIScheduler with plain DispatchQueue. I was just used to writing this kind of API 😅

I think if you want to avoid an async "tick" when you are already processing things on the main thread, `UIScheduler` can still be important. A `.receive(on: UIScheduler.shared)` will not incur the cost of a thread hop, but `.receive(on: DispatchQueue.main)` will.

**Comment by ollitapa** [comment]
On the TCA front, would you recommend to use `.receive(on: UIScheduler.shared)` directly inside the reducer? 

Or store it in the environment? So that there would be 
```swift
struct Env {
  var workScheduler: AnySchedulerOf<DispatchQueue>
  var mainScheduler: AnySchedulerOf<UIScheduler>
}
```

And use pipe those like `.subscribe(on: env.workScheduler).receive(on: env.mainScheduler)`

**Comment by stephencelis** [comment]
`UIScheduler` is probably most helpful in SwiftUI when you don't want to be too fussy about controlling the scheduler in your environment, but want to still retain some testability for non-delayed effects, since immediately scheduled work will be performed in the test without the usual thread hop of `receive(on: DispatchQueue.main)`.

Otherwise it's probably mostly useful in UIKit, where certain lifecycle events happen on the main thread and a further tick will cause layout glitches, like when a `UITableViewCell` is configured. In the end it should generally be useful in the same places that the ReactiveSwift scheduler is useful, but it's been awhile since I've lived in that pre-SwiftUI land, day-to-day 😅
