### ISSUE TITLE
Build documentation on Xcode14b5 for projects including `CombineSchedulers` fail

### ISSUE THREAD

**Issue by elkraneo** [pointfreeco/combine-schedulers#63]
**Describe the bug**
Only as a heads up, when trying to build documentation on Use Xcode14 beta 5 fails with not found symbol identifiers.

**To Reproduce**
Use Xcode14 beta 5 with a project that has the `CombineSchedulers` dependency and run "Build Documentation" from the Product menu 

**Expected behavior**
Documentation builds and `DocC` is exportable

**Screenshots**
![Screenshot 2022-08-15 at 11 29 09](https://user-images.githubusercontent.com/72805/184613385-f2aba286-b138-44d4-a03f-acbe05de6cd3.png)

**Environment**
 - Xcode 14.0 beta 5
 - Swift 5.7

**Comment by stephencelis** [comment]
This is an Xcode bug, unfortunately, that was introduced in Xcode 14 beta 4. Please file a duplicate feedback, if you can! Here's the one I filed:

https://gist.github.com/stephencelis/273fc81cf4f37c798a58ae18daf35813

Going to close this out, though, since it's a bug with Xcode and not our library.
